import "./globals.css";
import type { Metadata } from "next";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { Button } from "@/components/ui/button";
import { CircleHelp } from "lucide-react";
import {
  Dialog,
  DialogHeader,
  DialogContent,
  DialogDescription,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { auth } from "@/auth";
import LoginDialog from "@/components/login-dialog";
import Link from "next/link";
import PrivacyPolicy from "@/components/privacy-policy";

export const metadata: Metadata = {
  title: "Chatta med TNM094",
  // description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  const user = session?.user;

  return (
    <html lang="en">
      <body className="antialiased h-svh">
        <SidebarProvider className="h-full flex">
          <AppSidebar />
          <div className="h-full flex flex-col w-full">
            <header className="bg-white flex flex-row justify-between items-center drop-shadow-[0_0px_2px_rgba(0,0,0,0.05)] px-3 border-b border-gray-100">
              <SidebarTrigger />
              <Dialog>
                <DialogTrigger asChild>
                  <Button
                    className="hover:bg-white cursor-pointer"
                    variant={"ghost"}
                  >
                    <CircleHelp className="stroke-gray-400 size-6" />
                  </Button>
                </DialogTrigger>
                <DialogContent className="p-12 md:p-12 md:max-w-1/2 w-full max-h-full overflow-auto rounded-none md:rounded-md">
                  <div
                    className="overflow-auto md:max-h-96 h-full"
                    style={{
                      scrollbarColor: "#cbd5e1 #ffffff",
                    }}
                  >
                    <DialogTitle className="text-2xl mb-3">
                      Integritetspolicy för CHATTA MED TNM094
                    </DialogTitle>
                    <DialogDescription className="mb-4 text-gray-700">
                      Denna tjänst hjälper dig att besvara frågor om kursen
                      Medietekniskt Kandidatprojekt (TNM094) vid Linköpings
                      universitet.
                    </DialogDescription>
                    <PrivacyPolicy />
                  </div>
                </DialogContent>
              </Dialog>
            </header>
            <div className="grow overflow-y-auto">{children}</div>
            {!user && <LoginDialog />}
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
