import type { Metadata } from "next";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";

export const metadata: Metadata = {
  title: "Chatta med TNM094",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased h-svh overflow-hidden">
        <SidebarProvider className="h-full flex">
          <AppSidebar />
          <div className="h-full flex flex-col w-full">
            <header>
              <SidebarTrigger />
            </header>
            <div className="flex-grow overflow-auto">{children}</div>
            {/* <div className="h-[712.8px]">{children}</div> */}
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
