headings_for_splittning = [
    "sammanfattning",
    "teknisk utredning",
    "syfte",
    "frågeställning",
    "relaterat arbete",
    "metod",
    "resultat",
    "diskussion",
    "slutsatser",
    "projektplan",
    "system och tekniska lösningar",
    "grundläggande",
    "målplattform",
    "grundläggande systemutveckling",
    "utvecklingsmiljö",
    "projekthantering",
    "utvecklingsmetodik",
    "organisation",
    "tidsplan",
    "milstolpar och leverabler",
    "rutiner och principer",
    "mötesprinciper och rutiner",
    "rutiner för kravhantering och -spårning",
    "rutiner för versionshantering",
    "rutiner för systemarkitektur och programdesign",
    "rutiner för dokumentation",
    "rutiner för kvalitetssäkring",
    "etisk och samhällelig reflektion"
    ]